server:
  port: 8383


turbine:
  appConfig: author,credentials,post
  aggregator:
    clusterConfig: AUTHOR,CREDENTIALS,POST

eureka:
  instance:
    reaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    region: default
    registryFetchIntervalSeconds : 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
